server:
  port: 8090

spring:
  application:
    name: games-kotlin
  datasource:
    db-kind: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/games
    username: postgres
    password: postgres
  hibernate-orm:
    database:
      generation: drop-and-create
  liquibase:
    enabled: true
    driverClassName: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: "classpath:liquibase/changelog.yml"
  log:
    console:
      enable: true
      level: INFO
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"